# Generated by Django 4.1.6 on 2023-02-08 03:04

import blog.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('message_body', models.TextField(max_length=2000)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number is not valid in Iran Country', regex='^(\\+98|0)?9\\d{9}$')])),
                ('r_date', models.DateField(validators=[blog.models.allow_day])),
                ('r_time', models.TimeField(validators=[blog.models.open_hours])),
                ('person', models.PositiveIntegerField(validators=[blog.models.person_limit])),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('visit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.FileField(blank=True, null=True, upload_to='ps')),
                ('description', models.TextField(max_length=1200)),
                ('s_price', models.IntegerField()),
                ('t_price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
    ]
