# Generated by Django 4.1.3 on 2022-12-01 17:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
                ('s_price', models.IntegerField()),
                ('t_price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(related_name='products', to='blog.category')),
            ],
        ),
    ]
